platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotaliad/whiteboard
    tag: latest

inputs:
  - name: whiteboard
  - name: maintenance-mode

run:
  path: ./whiteboard/concourse/tasks/deploy-maintenance/deploy-maintenance.sh